import subprocess
import sys
from metadata import AUTHOR, URL, VERSION



def generate_build_info(version, author, url):
    content = f'''
# This file is automatically generated by build_release.py
# Do not edit manually.

VERSION = "{version}"
AUTHOR = "{author}"
URL = "{url}"
'''
    with open("src/data_integrity_tool/_build_info.py", "w") as f:
        f.write(content.strip())

def generate_version_file(version, author, url):
    # Parse version into tuple
    try:
        v_parts = [int(x) for x in version.split('.')]
        while len(v_parts) < 4:
            v_parts.append(0)
        file_ver = tuple(v_parts[:4])
    except ValueError:
        file_ver = (0, 0, 0, 0)
        
    version_str = str(file_ver).replace("(", "").replace(")", "")

    content = f'''
# UTF-8
#
# For more details about fixed file info 'ffi' see:
# http://msdn.microsoft.com/en-us/library/ms646997.aspx
VSVersionInfo(
  ffi=FixedFileInfo(
    # filevers and prodvers should be always a tuple with four items: (1, 2, 3, 4)
    # Set not needed items to zero 0.
    filevers={file_ver},
    prodvers={file_ver},
    # Contains a bitmask that specifies the valid bits 'flags'
    mask=0x3f,
    # Contains a bitmask that specifies the Boolean attributes of the file.
    flags=0x0,
    # The operating system for which this file was designed.
    # 0x4 - NT and there is no need to define OS for Windows 95/98/ME
    OS=0x40004,
    # The general type of file.
    # 0x1 - the file is an application.
    fileType=0x1,
    # The function of the file.
    # 0x0 - the function is not defined for this fileType
    subtype=0x0,
    # Creation date and time stamp.
    date=(0, 0)
    ),
  kids=[
    StringFileInfo(
      [
      StringTable(
        u'040904B0',
        [StringStruct(u'CompanyName', u'{author}'),
        StringStruct(u'FileDescription', u'Data Integrity Tool'),
        StringStruct(u'FileVersion', u'{version}'),
        StringStruct(u'InternalName', u'data-integrity-tool'),
        StringStruct(u'LegalCopyright', u'Copyright (c) {author}'),
        StringStruct(u'OriginalFilename', u'data-integrity-tool.exe'),
        StringStruct(u'ProductName', u'Data Integrity Tool'),
        StringStruct(u'ProductVersion', u'{version}'),
        StringStruct(u'Author', u'{author}'),
        StringStruct(u'URL', u'{url}')])
      ]), 
    VarFileInfo([VarStruct(u'Translation', [1033, 1200])])
  ]
)
'''
    with open("version_info.txt", "w", encoding="utf-8") as f:
        f.write(content.strip())

def run_pyinstaller():
    cmd = [
        sys.executable, "-m", "PyInstaller",
        "--noconfirm",
        "--onefile",
        "--console",
        "--name", "data-integrity-tool",
        "--clean",
        "--paths", "src",
        "--version-file", "version_info.txt",
        "run_app.py"
    ]
    print(f"Running: {' '.join(cmd)}")
    subprocess.check_call(cmd)

def main():
    print("Gathering build metadata...")
    print(f"Version: {VERSION}")
    print(f"Author: {AUTHOR}")
    print(f"URL: {URL}")
    
    print("Generating src/data_integrity_tool/_build_info.py...")
    generate_build_info(VERSION, AUTHOR, URL)
    
    print("Generating version_info.txt...")
    generate_version_file(VERSION, AUTHOR, URL)
    
    print("Running PyInstaller...")
    try:
        run_pyinstaller()
        print("\nBuild successful!")
    except subprocess.CalledProcessError:
        print("\nBuild failed!")
        sys.exit(1)

if __name__ == "__main__":
    main()
